### ISSUE TITLE
Cache directory is not existing and not generated after startup

### ISSUE THREAD

**Issue by simonswine** [wakaru44/my_dockerplace#2]
```
127.0.0.1 - - [25/Jan/2016 11:22:30] "GET /desktop HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/christian/my_dockerplace/dockerplace/main.py", line 22, in desktop
    "services": get_all_actions(app.config["DOCKER_SERVICES_HOME"]),
  File "/home/christian/my_dockerplace/dockerplace/system_calls.py", line 68, in get_all_actions
    "image": get_imageid(container)
  File "/home/christian/my_dockerplace/dockerplace/system_calls.py", line 33, in get_imageid
    img.save(savepath, "PNG")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1462, in save
    fp = builtins.open(fp, "wb")
IOError: [Errno 2] No such file or directory: 'dockerplace/static/cache/f92ea1839dc16d7396db358365da7066.png'

```

**Comment by wakaru44** [comment]
Fixed now. Thank you for the feedback :)

**Comment by simonswine** [comment]
:+1:
